num1 = int(input("enter numbers"))
num2 = int(input("enter numbers"))
num3 = int(input("enter numbers"))
maximum_number = max(num1, num2, num3)
minimum_number = min(num1,num2,num3)
print("maximum_number",maximum_number)
print("minimum_number",minimum_number)